name: Publish to nuget

on:
  push:
    branches:
      - main
    paths:
      - src/version.props

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Likvido.ApplicationInsights.Telemetry/Likvido.ApplicationInsights.Telemetry.csproj
          VERSION_FILE_PATH: version.props
          PACKAGE_NAME: Likvido.ApplicationInsights.Telemetry
          VERSION_REGEX: <Version>(.*)<\/Version>
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
